name: MAS Health - Serviceability Request
description: This option is to request a serviceability enhancement to the Health are of the Maximo Application Suite
title: "[Serviceability] What would you like to see added to MAS regarding serviceability?"
labels: ["Status - Requires L2 SME Review"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this serviceability request! Please replace the title above with a description of your request.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please provide your email address in case we need to get in touch with you for more information.
      placeholder: ex. mark@example.ibm.com
    validations:
      required: false
  - type: dropdown
    id: department
    attributes:
      label: Which business area do you work in?
      description: Please select the business area from the dropdown
      options:
        - Support
        - CDS
        - GBS
        - Development
        - Pre-sales
        - SWAT
    validations:
      required: true
  - type: dropdown
    id: field
    attributes:
      label: Does this request originate from the field or internal discovery
      description: Please select the origin area from the dropdown
      options:
        - Field (customer)
        - Internal (IBM requesting)
    validations:
      required: true
  - type: input
    id: case
    attributes:
      label: Salesforce Case Number
      description: If the request is field based please provide a salesforce case number if possible.
      placeholder: TS*********
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What serviceability feature would you like to see in the product going forward?
      description:  Please give as much detail as possible, including what the desired outcome would be if this request was put into the product.
      placeholder: Tell us what you see!
      value: Problem X occured, when doing Y when troubleshooting, a serviceability enhancement that does Z, would have been useful because..
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: MAS Version
      description: What version of MAS are you running?
      options:
        - 8.3 (Previous release)
        - 8.4 (Previous release)
        - 8.5 (Previous release)
        - 8.6 (Current release)
        - 8.7 (Future release)
        - 8.8 (Future release)
    validations:
      required: true
  - type: dropdown
    id: versionarea
    attributes:
      label: Health Version
      description: What version of Health are you running?
      options:
        - 8.0.0 (Previous release)
        - 8.1.0 (Previous release)
        - 8.2.0 (Current release)
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: What is the urgency this request is implimented into the product?
      description: Please select the severity of urgency from the drop-down
      multiple: true
      options:
        - Sev 1 - Business wide impoact - Fix in current release
        - Sev 2 - High impact, but not critical - Fix in next upcoming release is possible
        - Sev 3 - Medium impact - add in either of next 2 upcoming releases
        - Sev 4 - Low impact - Request to be added to plan, add to product when possible
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
